### ISSUE TITLE
Занятие 3.

### ISSUE THREAD

**Issue by stsdmchv** [Wolping/BelikovDV#1]
Задача 10 - реализована не верно. см условие.
Задача 4 - N можно сократить.
Почему решения задач 9 и 10 так сильно различаются? Мне нужны ваши решения, а не из интернета.

**Comment by Wolping** [comment]
Между 9 и 10 различия минимальны. Только еще 2 условия и ввод одной переменной

**Comment by stsdmchv** [comment]
> Между 9 и 10 различия минимальны. Только еще 2 условия и ввод одной переменной

Именно. Тогда почему складывается впечатление, что их решали два разных человека?

**Comment by Wolping** [comment]
Задачу 4 исправил
