### ISSUE TITLE
Занятие 5

### ISSUE THREAD

**Issue by stsdmchv** [Wolping/BelikovDV#2]
Задача 7 - решена не верно. Смысл задачи похож на 8.

**Comment by Wolping** [comment]
Исправил

**Comment by stsdmchv** [comment]
Продуманы не все условия. Проверка: 12334455660. Задача выдает: 5. Правильный: 2

**Comment by Wolping** [comment]
Вы перепутали условия задачи . В 7 : сколько элементов этой последовательности больше предыдущего элемента.

**Comment by Wolping** [comment]
Вы перепутали условия задачи . В 7 : сколько элементов этой последовательности больше предыдущего элемента. В этой последовательности их 5

**Comment by stsdmchv** [comment]
3 не больше 3. Соответственно последовательность которая должна быть посчитана это 1,2,3.

**Comment by Wolping** [comment]
Исправил
